### ISSUE TITLE
INIT_URL Format

### ISSUE THREAD

**Issue by xavier506** [CryptoLions/EOS-Boot-Steps-dawn4#1]
https://github.com/CryptoLions/EOS-Boot-Steps-dawn4/blob/8aaf810a84d75e35fe97c6140f1859ae6c0fcf6c/00_CONFIG.conf#L13

I noticed some examples  include "http://" and "https://" in the URL string. 

Is it necessary to include this prefix? does HTTP vs HTTPS make a difference?

Also noticed [examples](https://github.com/eosrio/bp-info-standard) that include "bp.json" or "[bp_info.json](https://medium.com/@bensig/eos-block-producer-guide-51b8194283b8)" as a suffix to the URL , should these URL suffixes be included?

**Comment by ansigroup** [comment]
I think its depend on bp.. but if will be tools that will use that url to get producer info - probably it should better include http://.
